
--DROP TABLE EVALUACION_RRHH

CREATE TABLE EVALUACION_RRHH
(
ID INT PRIMARY KEY IDENTITY(1,1),
EVALUADOR VARCHAR(60),
EVALUADO INT,
FEC_EVA DATE,
RESUMEN VARCHAR(250),
NOTA INT,
CAT_EVA VARCHAR(30),
FOREIGN KEY (EVALUADO) REFERENCES FORM_RRHH(ID)
);

