
--DROP TABLE EVALUACION_RRHH

CREATE TABLE EVALUACION_RRHH
(
ID INT PRIMARY KEY IDENTITY(1,1),
EVALUADOR VARCHAR(60),
FEC_EVA DATE,
RESUMEN VARCHAR(250),
NOTA INT,
CAT_EVA VARCHAR(30)
)

