--CREATE DATABASE RRHH;

--USE RRHH;
--drop table FORM_RRHH;

CREATE TABLE FORM_RRHH
(
ID			INT PRIMARY KEY IDENTITY(1,1),
NOMBRE		VARCHAR(30),
APELLIDO	VARCHAR(30),
EMAIL		VARCHAR(230),
TELEFONO	VARCHAR(15),
IDENTIFICACION VARCHAR(13),
GENERO		VARCHAR(11),
FECHA_NACIMIENTO DATE,
REFERENCIA	VARCHAR(50),
NIVEL_INGLES INT,
DIRECCION	VARCHAR(250),
ULTIMO_SALARIO INT ,
SALARIO_MINIMO INT,
FEC_TRA DATETIME
);
