--CREATE DATABASE RRHH;

--USE RRHH;

CREATE TABLE FORM_RRHH
(
ID			INT PRIMARY KEY IDENTITY(1,1),
NOMBRE		VARCHAR(30),
APELLIDO	VARCHAR(30),
EMAIL		VARCHAR(230),
TELEFONO	INT,
IDENTIFICACION VARCHAR(13),
GENERO		VARCHAR(11),
FECHA_NACIMIENTO DATE,
REFERNCIA	VARCHAR(50),
NIVEL_INGLES INT,
DIRECCION	VARCHAR(250),
ULTIMO_SALARIO INT ,
SALARIO_MINIMO INT
);
